print("Capitals of the world!")
print("Type dictionary to see all countries and capitals ")
print("Type test me to test yourself ")
user_input = input("What would you like to do: ")

capitals = {'AFGHANISTAN': 'KABUL', 'ALBANIA':'TIRANA', 'ALGERIA': 'ALGIERS',
'ANDORRA':'ANDORRA LA VELLA', 'ANGOLA': 'LUANDA', 'ANTIGUA & BARBUDA':'SAINT JOHNS', 'ARGENTINA': 'BUENOS AIRES',
'ARMENIA':'YEREVAN', 'AUSTRALIA': 'CANBERRA', 'AUSTRIA': 'VIENNA',
'AZERBAIJAN':'BAKU', 'BAHAMAS': 'NASSAU', 'BAHRAIN': 'MANAMA',
'BANGLADESH':'DHAKA', 'BARBADOS': 'BRIDGETOWN', 'BELARUS': 'MINSK',
'BELGIUM':'BRUSSELS', 'BELIZE': 'BELMOPAN', 'BENIN': 'PORTO-NOVO',
'BHUTAN':'THIMPHU', 'BOLIVIA': 'SUCRE', 'BOSNIA & HERZEGOVINA': 'SARAJEVO',
'BOTSWANA':'GABORONE', 'BRAZIL': 'BRASILIA', 'BRUNEI': 'BANDAR SERI BEGAWAN',
'BULGARIA':'SOFIA', 'BURKINA FASO': 'OUAGADOUGOU', 'BURUNDI': 'GITEGA, BUJUMBURA',
'CABO VERDE':'PRAIA', 'CAMBODIA': 'PHNOM PENH', 'CAMEROON': 'YAOUNDE', 'CANADA': 'OTTAWA',
'CENTRAL AFRICAN REPUBLIC': 'BANGUI', 'CHAD': 'N DJAMENA', 'CHILE': 'SANTIAGO',
'CHINA':'BEIJING', 'COLOMBIA': 'BOGOTÁ', 'COMOROS': 'MORONI', 'CONGO, DEMOCRATIC REPUBLIC': 'KINSHASA',
'CONGO, REPUBLIC': 'BRAZZAVILLE', 'COSTA RICA': 'SAN JOSE', 'CÔTE D IVOIRE': 'YAMOUSSOUKRO', 'CROATIA': 'ZAGREB',
'CUBA':'HAVANA', 'CYPRUS': 'NICOSIA', 'CZECHIA (Czech Republic)': 'PRAGUE', 'ECUADOR': 'QUITO', 'EGYPT': 'CAIRO',
'EL SALVADOR': 'SAN SALVADOR', 'EQUATORIAL GUINEA': 'MALABO', 'ERITREA': 'ASMARA', 'ESTONIA': 'TALLINN',
'ESWATINI (formerly Swaziland)': 'MBABANE', 'ETHIOPIA': 'ADDIS ABABA', 'FIJI': 'SUVA', 'FINLAND': 'HELSINKI',
'FRANCE': 'PARIS', 'GABON': 'LIBREVILLE', 'GAMBIA': 'BANJUL', 'GEORGIA': 'TBILISI', 'GERMANY': 'BERLIN',
'GHANA': 'ACCRA', 'GREECE': 'ATHENS', 'GRENADA': 'SAINT GEORGES', 'GUATEMALA': 'GUATEMALA CITY', 'GUINEA': 'CONAKRY',
'GUINEA-BISSAU': 'BISSAU', 'GUYANA': 'GEORGETOWN', 'HAITI': 'PORT-AU-PRINCE', 'HONDURAS': 'TEGUCIGALPA',
'HUNGARY': 'BUDAPEST', 'ICELAND': 'REYKJAVIK', 'INDIA': 'NEW DELHI', 'INDONESIA': 'JAKARTA', 'IRAN': 'TEHRAN',
'IRAQ': 'BAGHDAD', 'IRELAND': 'DUBLIN', 'israel':'Does not exist', 'ITALY': 'ROME', 'JAMAICA': 'KINGSTON',
'JAPAN': 'TOKYO', 'JORDAN': 'AMMAN', 'KAZAKHSTAN': 'NUR-SULTAN', 'KENYA': 'NAIROBI', 'KIRIBATI': 'SOUTH TARAWA',
'KOSOVO': 'PRISTINA', 'KUWAIT': 'KUWAIT CITY', 'KYRGYZSTAN': 'BISHKEK', 'LAOS': 'VIENTIANE', 'LATVIA': 'RIGA',
'LEBANON': 'BEIRUT', 'LESOTHO': 'MASERU', 'LIBERIA': 'MONROVIA', 'LIBYA': 'TRIPOLI', 'LIECHTENSTEIN': 'VADUZ',
'LITHUANIA': 'VILNIUS', 'LUXEMBOURG': 'LUXEMBOURG', 'MADAGASCAR': 'ANTANANARIVO', 'MALAWI': 'LILONGWE',
'MALAYSIA': 'KUALA LUMPUR', 'MALDIVES': 'MALE', 'MALI': 'BAMAKO', 'MALTA': 'VALLETTA', 'MARSHALL ISLANDS':
'MAJURO', 'MAURITANIA': 'NOUAKCHOTT', 'MAURITIUS': 'PORT LOUIS', 'MEXICO': 'MEXICO CITY', 'MICRONESIA': 'PALIKIR',
'MOLDOVA': 'CHISINAU', 'MONACO': 'MONACO', 'MONGOLIA': 'ULAANBAATAR', 'MONTENEGRO': 'PODGORICA', 'MOROCCO': 'RABAT',
'MOZAMBIQUE': 'MAPUTO', 'MYANMAR (Burma)': 'NAY PYI TAW', 'NAMIBIA': 'WINDHOEK', 'NAURU': 'YAREN DISTRICT',
'NEPAL': 'KATHMANDU', 'NETHERLANDS': 'AMSTERDAM', 'NEW ZEALAND': 'WELLINGTON', 'NICARAGUA': 'MANAGUA',
'NIGER': 'NIAMEY', 'NIGERIA': 'ABUJA', 'NORTH KOREA': 'PYONGYANG', 'NORTH MACEDONIA (formerly Macedonia)': 'SKOPJE',
'NORWAY': 'OSLO', 'OMAN': 'MUSCAT', 'PAKISTAN': 'ISLAMABAD', 'PALAU': 'NGERULMUD', 'PALESTINE': 'EAST JERUSALEM',
'PANAMA': 'PANAMA CITY', 'PAPUA NEW GUINEA': 'PORT MORESBY', 'PARAGUAY': 'ASUNCIÓN', 'PERU': 'LIMA',
'PHILIPPINES': 'MANILA', 'POLAND': 'WARSAW', 'PORTUGAL': 'LISBON', 'QATAR': 'DOHA', 'ROMANIA': 'BUCHAREST',
'RUSSIA': 'MOSCOW', 'RWANDA': 'KIGALI', 'SAINT KITTS & NEVIS': 'BASSETERRE', 'SAINT LUCIA': 'CASTRIES',
'SAINT VINCENT & THE GRENADINES': 'KINGSTOWN', 'SAMOA': 'APIA', 'SAN MARINO': 'SAN MARINO',
'SÃO TOMÉ & PRÍNCIPE': 'SÃO TOMÉ', 'SAUDI ARABIA': 'RIYADH', 'SENEGAL': 'DAKAR', 'SERBIA': 'BELGRADE',
'SEYCHELLES': 'VICTORIA', 'SIERRA LEONE': 'FREETOWN', 'SINGAPORE': 'SINGAPORE', 'SLOVAKIA': 'BRATISLAVA',
'SLOVENIA': 'LJUBLJANA', 'SOLOMON ISLANDS': 'HONIARA', 'SOMALIA': 'MOGADISHU', 'SOUTH AFRICA': 'CAPE TOWN',
'SOUTH KOREA': 'SEOUL', 'SOUTH SUDAN': 'JUBA', 'SPAIN': 'MADRID', 'SRI LANKA': 'COLOMBO, SRI JAYAWARDENEPURA KOTTE',
'SUDAN': 'KHARTOUM', 'SURINAME': 'PARAMARIBO', 'SWEDEN': 'STOCKHOLM', 'SWITZERLAND': 'BERN', 'SYRIA': 'DAMASCUS',
'TAJIKISTAN': 'DUSHANBE', 'TANZANIA': 'DODOMA', 'THAILAND': 'BANGKOK', 'TIMOR-LESTE': 'DILI', 'TOGO': 'LOMÉ',
'TONGA': 'NUKUʻALOFA', 'TRINIDAD & TOBAGO': 'PORT OF SPAIN', 'TUNISIA': 'TUNIS', 'TÜRKIYE(Turkey)': 'ANKARA',
'TURKMENISTAN': 'ASHGABAT', 'TUVALU': 'FUNAFUTI', 'UGANDA': 'KAMPALA', 'UKRAINE': 'KIEV',
'UNITED ARAB EMIRATES (UAE)': 'ABU DHABI', 'UNITED KINGDOM (UK)': 'LONDON',
'UNITED STATES OF AMERICA (USA)': 'WASHINGTON, D.C.', 'URUGUAY': 'MONTEVIDEO', 'UZBEKISTAN': 'TASHKENT',
'VANUATU': 'PORT VILA', 'VATICAN CITY': 'VATICAN CITY', 'VENEZUELA': 'CARACAS', 'VIETNAM': 'HANOI',
'YEMEN': 'SANAA', 'ZAMBIA': 'LUSAKA', 'ZIMBABWE': 'HARARE'}


if user_input == 'dictionary':
    for key,value in capitals.items():
     print(key,value)

if user_input.lower() == "test me":
    import random

    country = random.choice(list(capitals.keys()))
    user_guess = input("Enter the capital of {} (note all answers must be in CAPS): ".format(country))
    correct_capital = capitals[country]

    if user_guess.lower() == correct_capital.lower():
        print("Correct! The capital of {} is {}".format(country, correct_capital))
    else:
        print("Incorrect! The capital of {} is {}".format(country, correct_capital))
